// Для установки смотреть [[Участник:Lockal/monobook.js]]
popupStrings = {
  'article': 'статья',
  'category': 'категория',
  'categories': 'категорий',
  'image': 'изображение',
  'images': 'изображений',
  'stub': 'stub',
  'section stub': 'stub-секция',
  'Empty page': 'Пустая страница',
  'kB': 'кб',
  'bytes': 'байт',
  'day': 'день',
  'days': 'дней',
  'hour': 'час',
  'hours': 'часов',
  'minute': 'минута',
  'minutes': 'минут',
  'second': 'секунда',
  'seconds': 'секунд',
  'week': 'неделя',
  'weeks': 'недель',
  'search': 'поиск',
  'SearchHint': 'Найти статьи, содержащие строку %s',
  'web': 'web',
  'global': 'глобальный',
  'globalSearchHint': 'Искать строку %s во всех языковых разделах Википедии',
  'googleSearchHint': 'Искать %s в Google',
  'more...': 'дальше...',
  'actions': 'действия',         ///// view articles and view talk
  'popupsMenu': 'тултипы',
  'disable previews': 'отключить предпросмотр',
  'togglePreviewsHint': 'Предварительный просмотр страниц из всплывающих окон.',
  'toggle previews': 'предварительный просмотр',
  'reset': 'сброс',
  'disable': 'отключить всплывающие окна',
  'disablePopupsHint': 'Отключить всплывающие окна на этой странице. Для включения обновите страницу.',
  'purgePopupsHint': 'Очистить кэш всплывающих окон.',
  'PopupsHint': 'Очистить кэш всплывающих окон.',
  'spacebar': 'пространство',
  'view': 'просмотр',
  'view article': 'просмотр статьи',
  'viewHint': 'Перейти к %s',
  'talk': 'обсуждение',
  'talk page': 'обсуждение',
  'this&nbsp;revision': 'текущая версия',
  'revision %s of %s': 'версия %s от %s',
  'Revision %s of %s': 'Версия %s от %s',
  'the revision prior to revision %s of %s': 'от текущей версии до версии %s страницы %s',
  'Toggle image size': 'Кликните, чтобы увеличить изображение',
  'del': 'удалить',                 ///// delete, protect, move
  'delete': 'удалить',
  'deleteHint': 'Удалить %s',
  'undeleteShort': '←',
  'UndeleteHint': 'Показать журнал удалений страницы %s',
  'protect': 'защитить',
  'protectHint': 'Защитить страницу %s',
  'unprotectShort': '←',
  'unprotectHint': 'Разблокировать страницу %s',
  'move': 'переименовать',
  'move page': 'переименовать',
  'MovepageHint': 'Переименовать страницу %s',
  'edit': 'править',               ///// edit articles and talk
  'edit article': 'править',
  'editHint': 'Редактировать статью %s',
  'edit talk': 'править обсуждение',
  'new': 'новая',
  'new topic': 'новая секция',
  'newSectionHint': 'Добавить комментарий к обсуждению статьи %s',
  'null edit': 'null-правка',
  'nullEditHint': 'Записать страницу %s без изменений',
  'hist': 'история',               ///// history, diffs, editors, related
  'history': 'история',
  'historyHint': 'Журнал изменений страницы %s',
  'last': 'пред.',
  'lastEdit': 'Предыдущая правка',
  'show last edit': 'последняя правка',
  'Show the last edit': 'Показать результат последней правки',
  'lastContrib': 'последний вклад',
  'last set of edits': 'последние правки',
  'lastContribHint': 'Показать вклад участника, редактировавшего последний раз статью',
  'cur': 'текущ.',
  'diffCur': 'текущ.',
  'Show changes since revision %s': 'Показать изменения, начиная с %s',
  '%s old': '%s назад', // as in 4 weeks old
  'oldEdit': 'пред.',
  'purge': 'очистить кэш',
  'purgeHint': 'Запросить свежую копию %s',
  'raw': 'исходный код',
  'rawHint': 'Просмотреть исходный код страницы %s',
  'render': 'HTML',
  'renderHint': 'Показать чистую HTML версию страницы %s',
  'Show the edit made to get revision': 'Показать правки для журнала изменений',
  'sinceMe': 'к моим правкам',
  'changes since mine': 'к моим правкам',
  'sinceMeHint': 'Показать изменения с момента Вашего последнего редактирования',
  'Couldn\'t find an edit by %s\nin the last %s edits to\n%s': 'Не найдено правок %s\nin последних %s правок \n%s',
  'eds': 'редакторы',
  'editors': 'редакторы',
  'editorListHint': 'Список участников, редактировавших статью %s',
  'related': 'связанные правки',
  'relatedChanges': 'связанные правки',
  'related changes': 'связанные правки',
  'RecentchangeslinkedHint': 'Показать изменения в статье, родственные %s',
  'editOld': 'редактировать',          ///// edit old version, or revert
  'rv': 'возврат',
  'revert': 'возврат',
  'revertHint': 'Отменить %s',
  'undo': 'отмена',
  'undoHint': 'Редактировать версию до правок',
  'defaultpopupRedlinkSummary': 'Удаление ссылки на пустую страницу [[%s]] с помощью [[:en:Wikipedia:Tools/Navigation_popups|всплывающих окон]]',
  'defaultpopupFixDabsSummary': 'Исправление неоднозначности [[%s]] ⇒ [[%s]] с помощью [[ВП:NavPopUp|всплывающих окон]]',
  'defaultpopupFixRedirsSummary': 'Развёртывание редиректа [[%s]] на статью [[%s]] с помощью [[ВП:NavPopUp|всплывающих окон]]',
  'defaultpopupExtendedRevertSummary': 'Возврат к версии %s от %s, к версии %s с помощью [[ВП:NavPopUp|всплывающих окон]]',
  'defaultpopupRevertToPreviousSummary': 'Возврат к версии %s с помощью [[ВП:Всплывающие окна|всплывающих окон]]',
  'defaultpopupRevertSummary': 'Возврат к версии %s с помощью [[ВП:Всплывающие окна|всплывающих окон]]',
  'defaultpopupQueriedRevertToPreviousSummary': 'Возврат к версии $1 ($2) от $3 с помощью [[ВП:NavPopUp|всплывающих окон]]',
  'defaultpopupQueriedRevertSummary': 'Возврат к версии [[Участник:$3|$3]] от $2 ($1) с помощью [[ВП:NavPopUp|всплывающих окон]]',
  'defaultpopupRmDabLinkSummary': 'Удалена ссылка [[%s]] с помощью [[ВП:Всплывающие окна|всплывающих окон]]',
  'Redirects': 'Перенаправление', // as in Redirects to ...
  ' to ': ' на ',           // as in Redirects to ...
  'Bypass redirect': 'Обход перенаправления',
  'Fix this redirect': 'Исправить редирект',
  'disambig': 'неоднозначность',          ///// add or remove dab etc.
  'disambigHint': 'Исправить неоднозначность, установив ссылку на [[%s]]',
  'Click to disambiguate this link to:': 'Исправить неоднозначность:',
  'remove this link': 'удалить эту ссылку',
  'remove all links to this page from this article': 'удалить все ссылки на эту страницу из статьи',
  'remove all links to this disambig page from this article': 'удалить все ссылки на эту неоднозначную страницу из статьи',
  'mainlink': 'ссылка',          ///// links, watch, unwatch
  'wikiLink': 'ссылка',
  'wikiLinks': 'ссылок',
  'links here': 'ссылки сюда',
  'whatLinksHere': 'ссылки сюда',
  'what links here': 'ссылки сюда',
  'WhatlinkshereHint': 'Список всех страниц, которые ссылаются на %s',
  'unwatchShort': '←',
  'watchThingy': 'следить',  // called watchThingy because {}.watch is a function
  'watchHint': 'Добавить страницу %s в ваш список наблюдения',
  'unwatchHint': 'Удалить страницу %s из вашего списка наблюдения',
  'Only found one editor: %s made %s edits': 'Найден только один редактор: %s сделал %s правок',
  '%s seems to be the last editor to the page %s': '%s был последним редактором страницы %s',
  'rss': 'rss',
  'Diff truncated for performance reasons': 'Не удалось получить описание изменений',
  'Old revision': 'Предыдущая версия',
  'New revision': 'Текущая версия',
  'Something went wrong :-(': 'Ошибка :(',
  'Empty revision, maybe non-existent': 'Пустая, возможно не существующая версия',
  'Unknown date': 'Неизвестная дата',
  'Empty category': 'Пустая категория',
  'Category members (%s shown)': 'Страницы в категории (показано %s)',
  'No image links found': 'Не найдено ссылок на изображение',
  'File links': 'Ссылки на файл',
  'not commons': 'Изображения с таким именем нет в Wikimedia Commons.',
  'commons only': 'Это изображение находится в Wikimedia Commons.',
  'No image found': 'Изображение не найдено',
  'commons dupe': 'Такой файл уже есть в хранилище файлов Wikimedia Commons.',
  'commons conflict': 'Файл с этим именем уже существует в хранилище файлов Wikimedia Commons.',
  'user': 'участник',               ///// user page, talk, email, space
  'user&nbsp;page': 'участник',
  'user talk': 'обсуждение',
  'edit user talk': 'править',
  'leave comment': 'комментировать',
  'email': 'email',
  'email user': 'отправить email',
  'EmailuserHint': 'Отправить email %s',
  'space': 'подстраницы', // short form for userSpace link
  'PrefixindexHint': 'Показать страницы в пространстве имён %s',
  'count': 'счётчик',             ///// contributions, tree, log
  'edit counter': 'счётчик правок',
  'katelinkHint': 'Cчётчик правок пользователя %s',
  'contribs': 'вклад',
  'contributions': 'вклад',
  'ContributionsHint': 'Список страниц, которые изменял участник %s',
  'tree': 'полностью',
  'contribsTreeHint': 'Просмотр вклада %s по пространству имён и названию статей',
  'log': 'журнал',
  'user log': 'журнал',
  'userLogHint': 'Служебная:Log',
  'arin': 'whois',             ///// ARIN lookup, block user or IP
  'Look up %s in ARIN whois database': 'Найти %s в базе данных ARIN whois',
  'unblockShort': '←',
  'block': 'блокировать',
  'block user': 'блокировать',
  'IpblocklistHint': 'Разблокировать %s',
  'BlockipHint': 'Защитить %s от редактирования',
  'block log': 'журнал блокировок',
  'blockLogHint': 'Показать журнал блокировок для %s',
  'protectLogHint': 'Показать журнал защит для %s',
  'pageLogHint': 'Показать историю правок %s',
  'deleteLogHint': 'Показать журнал удалений для %s',
  'Invalid %s %s': 'Действие %s ошибочно: %s',
  'Enter a non-empty edit summary or press cancel to abort': 'Заполните описание изменений или нажмите кнопку Отменить',
  'Failed to get revision information, please edit manually.\n\n': 'Ошибка при получении журнала правок страницы. Пожалуйста, отредактируйте страницу вручную.\n\n',
  'The %s button has been automatically clicked. Please wait for the next page to load.': 'Автоматический переход по %s. Пожалуйста, дождитесь завершения загрузки страницы.',
  'Could not find button %s. Please check the settings in your javascript file.': 'Кнопка %s не найдена. Пожалуйста, проверьте настройки в вашем javascript файле.',
  'Open full-size image': 'Открыть полноразмерное изображение',
  'zxy': 'zxy'
};